name: circle_time_progress
description: "A customizable gradient circular progress indicator for Flutter, perfect for fasting timers or similar use cases."
version: 0.0.1
homepage: https://github.com/JamshaidMallik/circle_time_progress
repository: https://github.com/JamshaidMallik/circle_time_progress

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
